services:
  - type: web
    name: taskmaster-site
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn taskmaster.wsgi"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: taskmaster.settings
    plan: free
