# Generated by Django 5.1.7 on 2025-04-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Аты-жөні')),
                ('description', models.TextField(verbose_name='Тапсырма сипаттамасы')),
                ('file', models.FileField(blank=True, null=True, upload_to='orders/', verbose_name='Қосымша файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жіберілген уақыт')),
            ],
        ),
    ]
